### ISSUE TITLE
Setup CI to run tests in PRs

### ISSUE THREAD

**Issue by nlopin** [freenowtech/react-polygon-editor#36]

**Comment by dornelasnelson** [comment]
With the current actions we have, every commit done to the MR is running the build & test actions. Do you think we need a separate action for tests in PRs? Not sure if it's necessary. 

My first few commits were not running the actions because I was having the github account issues using the old one without the verified email. Now after I've fixed it and I'm using the correct user it's always running the actions in every commit.
